version: 2.1
jobs:
  replay-upload:
    docker:
      - image: cimg/node:18.4.0-browsers
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: "npm ci"
      - run:
          name: "Run Cypress Tests"
          command: 'npx cypress run --browser "Replay Firefox"'
          environment:
            RECORD_ALL_CONTENT: 1
            RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata.log
      - run:
          name: "Upload to Replay"
          when: always
          command: |
            npm i -g @replayio/replay@latest
            export RECORD_REPLAY_METADATA_SOURCE_COMMIT_TITLE="$(git log --format=%s -n 1)"
            replay metadata --init --keys source --warn
            replay ls
            replay upload-all --api-key $REPLAY_API_KEY
workflows:
  cypress-test-workflow:
    jobs:
      - replay-upload:
          context: replayable