name: Playwright Tests
on: [pull_request]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Build site
        run: pnpm run build
        env:
          NEXT_PUBLIC_SITE_URL: 'https://docs.replay.io'
      - name: Install Replay Chromium
        run: pnpx replayio install
      - name: Run Playwright tests
        run: pnpm test
        env:
          BASE_URL: http://127.0.0.1:3000
          REPLAY_API_KEY: ${{ secrets.REPLAY_API_KEY }}
